POST  http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
    "fName": "Amir",
    "lName": "Maghami",
    "phone": "09198881400",
    "password": "09198881400",
    "confirmPassword": "09198881400"
}