DELETE http://localhost:5000/api/containers/63ecb98c63ad99f2c56cd9dc HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6IjA5MTk4ODgxNDAwIiwibmFtZSI6IkFtaXIgTWFnaGFtaSIsIl9pZCI6IjYzZmFlNTE4MDM5MWU3NjAxNWNiMjU1ZSIsImlhdCI6MTY3NzQ3NzU5OH0.GSGX0jjJoeu24rkcDBM7UIF0mBOalJzl3M6_R_soS18
content-type: application/json