PUT  http://localhost:5000/api/containers/63ecb98c63ad99f2c56cd9db HTTP/1.1
content-type: application/json

{

    "owner_id": "",
    "created_at": "2023-02-13T12:51:26.354000",
    "updated_at": "2023-02-14T06:56:51.722000",
    "title": "zzzzzعنasdasasasasasasasasasasasasasasasasasasasasasasasوان نظرسنجی",
    "description": "توضیحات تست عملکرد",
    "container_type": 2,
    "is_active": true,
    "display_setting": {
        "show_progress": false,
        "show_next_button": true,
        "show_previous_button": true
    },
    "items": [
        {
            "owner_id": "a6669786-308c-4455-91ca-412b541e770a",
            "created_at": "2023-02-13T12:19:39.754000",
            "updated_at": "2023-02-13T12:19:49.706000",
            "id": "7ced1e74-0099-4cf4-95ab-72920bd40296",
            "question_type": "welcome",
            "title": "ertert",
            "description": "etertertert",
            "position": 1,
            "picture": "storage/202302/95b3dc8622feccad9350483c875f726b.png",
            "display_setting": {
                "is_visible": true,
                "is_required": false,
                "show_question_number": true,
                "welcome": {
                    "button_label": "ertertertert"
                }
            }
        },
        {
            "owner_id": "a6669786-308c-4455-91ca-412b541e770a",
            "created_at": "2023-02-13T13:20:07.553000",
            "updated_at": "2023-02-13T13:20:07.553000",
            "id": "e74d146d-ec3a-4724-aeb7-8f1ac051a024",
            "question_type": "radio",
            "title": "tryrtyrty",
            "description": "rtyry",
            "position": 1,
            "picture": "",
            "options": [
                {
                    "label": "",
                    "value": 1,
                    "point": 0,
                    "position": 0,
                    "picture": "",
                    "answer": 0
                }
            ],
            "score": {
                "coefficient": 1,
                "value": 0,
                "feedback_correct_answer": "",
                "feedback_wrong_answer": ""
            },
            "display_setting": {
                "is_visible": true,
                "is_required": false,
                "show_question_number": true,
                "radio": {
                    "show_vertical": false,
                    "show_randomize": false,
                    "is_dropdown": false
                }
            }
        },
        {
            "owner_id": "a6669786-308c-4455-91ca-412b541e770a",
            "created_at": "2023-02-13T13:20:23.037000",
            "updated_at": "2023-02-13T13:20:23.037000",
            "id": "8b9065b7-2ffc-4ec1-8744-c510e78c0245",
            "question_type": "end",
            "title": "werwer",
            "description": "werwerwr",
            "position": 2,
            "picture": "",
            "display_setting": {
                "is_visible": true,
                "is_required": false,
                "show_question_number": true,
                "end": {
                    "is_default": false,
                    "is_redirect": false,
                    "redirect": "DESIRED_LINK",
                    "url": "",
                    "button_label": "پایان"
                }
            }
        }
    ],
    "exam_setting": {
        "time": {
            "is_active": true,
            "value": "04:04:04"
        },
        "show_correct_answer": true,
        "show_performance": true,
        "evaluation_labels": [
            {
                "label": "خوب",
                "order": 2
            },
            {
                "label": "بد",
                "order": 1
            }
        ],
        "show_answer_sheet": false
    },
    "total_answer": 0,
    "total_poll": 0,
    "average_score": 0,
    "is_exam": false,
    "is_welcome": false,
    "max_score": 0,
    "exam_score": 0,
    "template": {
        "owner_id": "a6669786-308c-4455-91ca-412b541e770a",
        "created_at": "2023-02-13T13:20:39.572000",
        "updated_at": "2023-02-13T13:20:39.572000",
        "id": "dca9381e-d09f-480e-87e3-f9da65fffe39",
        "background": {
            "background_color": "#f1f1f1",
            "image": "storage/202302/95b3dc8622feccad9350483c875f726b.png",
            "size": "cover",
            "is_repeat": false,
            "opacity": 0,
            "position": "top left"
        },
        "question_color": "#212121",
        "description_color": "#414141",
        "answer_color": "#616161",
        "progress_color": "#FF00FA",
        "button_color": "#D9AD73"
    }
}